# Generated by Django 3.1.7 on 2021-02-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210225_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='picture',
            field=models.ImageField(default=None, upload_to='', verbose_name='Картинка'),
        ),
    ]
