# Generated by Django 3.1.7 on 2021-02-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210225_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='picture',
            field=models.ImageField(default='green.png', upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='picture',
            field=models.ImageField(default='green.png', upload_to='', verbose_name='Картинка'),
        ),
    ]
