# Generated by Django 3.1.7 on 2021-02-26 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_country_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Текст')),
                ('tour', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.tour')),
            ],
        ),
    ]
